#!/bin/sh
set -eu

<<INTRO
Series Name:    Star Warp
Code Name:      A new hope
Author:         Codegenki
Description:    Supporting script for OS mudule
Usage:          Add to your conkyrc config block:
                lua_load = '~/.config/conky/scripts/script.lua',
                lua_draw_hook_post = 'main',
                lua_draw_hook_pre = 'some_function'
INTRO

# It seems that in conky the execi command will start before curl has completely
# written the file. For some reason adding a sleep before calling curl fixes it.
sleep 2

earthquake_list="$HOME/.cache/conky/earthquake.json"

curl -s "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.geojson" -o "$earthquake_list"


